function p_endeff = p560_p_endeff_generated(in1)
%P560_P_ENDEFF_GENERATED
%    P_ENDEFF = P560_P_ENDEFF_GENERATED(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    30-Jun-2019 20:59:53

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q2);
t6 = sin(q3);
t7 = sin(q1);
p_endeff = [t7.*1.5005e-1+t2.*t3.*4.318e-1+t2.*t3.*t4.*2.03e-2-t2.*t3.*t6.*4.318e-1-t2.*t4.*t5.*4.318e-1-t2.*t5.*t6.*2.03e-2,t2.*(-1.5005e-1)+t3.*t7.*4.318e-1+t3.*t4.*t7.*2.03e-2-t3.*t6.*t7.*4.318e-1-t4.*t5.*t7.*4.318e-1-t5.*t6.*t7.*2.03e-2,t5.*4.318e-1+(4.322769135635166e3.*cos(q2+q3-atan(4.701250578971746e-2)))./1.0e4];
