function M = sw_model_M(in1)
%SW_MODEL_M
%    M = SW_MODEL_M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Aug-2019 17:52:55

r1 = in1(5,:);
r2 = in1(6,:);
theta1 = in1(3,:);
theta2 = in1(4,:);
t2 = cos(theta1);
t3 = (r1.*t2)./2.0;
t4 = r1.^2;
t5 = sin(theta1);
t6 = cos(theta2);
t7 = (r2.*t6)./2.0;
t8 = r2.^2;
t9 = sin(theta2);
t10 = t5./2.0;
t11 = t2.^2;
t12 = t5.^2;
t13 = t9./2.0;
t14 = t6.^2;
t15 = t9.^2;
M = reshape([2.0,0.0,t3,t7,t10,t13,0.0,1.0,0.0,0.0,0.0,0.0,t3,0.0,(t4.*t11)./2.0+(t4.*t12)./2.0,0.0,0.0,0.0,t7,0.0,0.0,(t8.*t14)./2.0+(t8.*t15)./2.0,0.0,0.0,t10,0.0,0.0,0.0,t11./2.0+t12./2.0,0.0,t13,0.0,0.0,0.0,0.0,t14./2.0+t15./2.0],[6,6]);
