function M = sw_model_M(in1)
%SW_MODEL_M
%    M = SW_MODEL_M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Sep-2019 17:45:03

r1 = in1(5,:);
r2 = in1(6,:);
theta1 = in1(3,:);
theta2 = in1(4,:);
t2 = sin(theta1);
t3 = sin(theta2);
t4 = cos(theta1);
t5 = cos(theta2);
t6 = r1.*t4;
t7 = r1.*t2;
t8 = r1.^2;
t9 = r2.*t5;
t10 = r2.*t3;
t11 = r2.^2;
t12 = t4.^2;
t13 = t2.^2;
t14 = t5.^2;
t15 = t3.^2;
M = reshape([3.0,0.0,t6,t9,t2,t3,0.0,3.0,t7,t10,-t4,-t5,t6,t7,t8.*t12+t8.*t13,0.0,0.0,0.0,t9,t10,0.0,t11.*t14+t11.*t15,0.0,0.0,t2,-t4,0.0,0.0,t12+t13,0.0,t3,-t5,0.0,0.0,0.0,t14+t15],[6,6]);
