function [out1,out2] = sw_model_fkine(in1)
%SW_MODEL_FKINE
%    [OUT1,OUT2] = SW_MODEL_FKINE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Aug-2019 17:52:55

px = in1(1,:);
py = in1(2,:);
r1 = in1(5,:);
r2 = in1(6,:);
theta1 = in1(3,:);
theta2 = in1(4,:);
out1 = [px+r1.*sin(theta1);py-r1.*cos(theta1)];
if nargout > 1
    out2 = [px+r2.*sin(theta2);py-r2.*cos(theta2)];
end
