function fe = sw_model_fe(in1,in2,in3)
%SW_MODEL_FE
%    FE = SW_MODEL_FE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Sep-2019 12:28:51

fc1x = in3(4,:);
fc1y = in3(5,:);
fc2x = in3(6,:);
fc2y = in3(7,:);
r1 = in1(5,:);
r2 = in1(6,:);
r1d = in2(5,:);
r2d = in2(6,:);
r1tau = in3(2,:);
r2tau = in3(3,:);
tau = in3(1,:);
theta1 = in1(3,:);
theta2 = in1(4,:);
theta1d = in2(3,:);
theta2d = in2(4,:);
t2 = cos(theta1);
t3 = sin(theta1);
t4 = cos(theta2);
t5 = sin(theta2);
fe = [fc1x+fc2x;fc1y+fc2y;tau-theta1d.*1.0e1+fc1x.*r1.*t2+fc1y.*r1.*t3;tau-theta2d.*1.0e1+fc2x.*r2.*t4+fc2y.*r2.*t5;r1.*-1.0e3-r1d.*3.0e2+r1tau.*1.0e2+fc1x.*t3-fc1y.*t2+1.0e3;r2.*-1.0e3-r2d.*3.0e2+r2tau.*1.0e2+fc2x.*t5-fc2y.*t4+1.0e3];
