function C = sw_model_C(in1,in2)
%SW_MODEL_C
%    C = SW_MODEL_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    21-Aug-2019 12:57:00

r1 = in1(5,:);
r2 = in1(6,:);
r1d = in2(5,:);
r2d = in2(6,:);
theta1 = in1(3,:);
theta2 = in1(4,:);
theta1d = in2(3,:);
theta2d = in2(4,:);
vx = in2(1,:);
t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta1);
t5 = r1d.*t4;
t6 = r1.*t2.*theta1d;
t7 = t5+t6+vx;
t8 = r1d.*t2;
t11 = r1.*t4.*theta1d;
t9 = t8-t11;
t10 = t5+t6;
t12 = sin(theta2);
t13 = r2d.*t12;
t14 = r2.*t3.*theta2d;
t15 = t13+t14+vx;
t16 = r2d.*t3;
t19 = r2.*t12.*theta2d;
t17 = t16-t19;
t18 = t13+t14;
t20 = (t2.*t7)./1.0e1;
t21 = (t3.*t15)./1.0e1;
C = [-theta1d.*((r1d.*t2)./1.0e1-(r1.*t4.*theta1d)./1.0e1)-theta2d.*((r2d.*t3)./1.0e1-(r2.*t12.*theta2d)./1.0e1)-(r1d.*t2.*theta1d)./1.0e1-(r2d.*t3.*theta2d)./1.0e1;-1.1772e1;-r1d.*(t20-(t4.*t9)./1.0e1+(r1.*t2.^2.*theta1d)./1.0e1+(r1.*t4.^2.*theta1d)./1.0e1)-r1.*t4.*(9.81e2./1.0e3)+(t7.*t9)./1.0e1-(t9.*t10)./1.0e1+theta1d.*((r1.*t4.*t7)./1.0e1-(r1.*t4.*t10)./1.0e1);-r2d.*(t21-(t12.*t17)./1.0e1+(r2.*t3.^2.*theta2d)./1.0e1+(r2.*t12.^2.*theta2d)./1.0e1)-r2.*t12.*(9.81e2./1.0e3)+(t15.*t17)./1.0e1-(t17.*t18)./1.0e1+theta2d.*((r2.*t12.*t15)./1.0e1-(r2.*t12.*t18)./1.0e1);t2.*(9.81e2./1.0e3)-theta1d.*(t20-(t2.*t10)./1.0e1)+(t2.*t7.*theta1d)./1.0e1-(t4.*t9.*theta1d)./1.0e1;t3.*(9.81e2./1.0e3)-theta2d.*(t21-(t3.*t18)./1.0e1)+(t3.*t15.*theta2d)./1.0e1-(t12.*t17.*theta2d)./1.0e1];
