function M = sw_model_M(in1)
%SW_MODEL_M
%    M = SW_MODEL_M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Sep-2019 12:28:51

r1 = in1(5,:);
r2 = in1(6,:);
theta1 = in1(3,:);
theta2 = in1(4,:);
t2 = sin(theta1);
t3 = sin(theta2);
t4 = cos(theta1);
t5 = cos(theta2);
t6 = (r1.*t4)./1.0e1;
t7 = (r1.*t2)./1.0e1;
t8 = (r2.*t5)./1.0e1;
t9 = (r2.*t3)./1.0e1;
t10 = t2./1.0e1;
t11 = t3./1.0e1;
M = reshape([6.0./5.0,0.0,t6,t8,t10,t11,0.0,6.0./5.0,t7,t9,t4.*(-1.0./1.0e1),t5.*(-1.0./1.0e1),t6,t7,r1.^2./1.0e1,0.0,0.0,0.0,t8,t9,0.0,r2.^2./1.0e1,0.0,0.0,t10,t4.*(-1.0./1.0e1),0.0,0.0,1.0./1.0e1,0.0,t11,t5.*(-1.0./1.0e1),0.0,0.0,0.0,1.0./1.0e1],[6,6]);
