function fe = sw_model_fe(in1,in2,in3)
%SW_MODEL_FE
%    FE = SW_MODEL_FE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Aug-2019 17:52:55

fc1y = in3(5,:);
fc2y = in3(6,:);
r1 = in1(5,:);
r2 = in1(6,:);
r1d = in2(5,:);
r2d = in2(6,:);
r1s = in3(3,:);
r2s = in3(4,:);
tau1 = in3(1,:);
tau2 = in3(2,:);
theta1 = in1(3,:);
theta2 = in1(4,:);
fe = [0.0;fc1y+fc2y;tau1+fc1y.*r1.*sin(theta1);tau2+fc2y.*r2.*sin(theta2);r1.*-1.0e2-r1d.*1.0e1+r1s.*1.0e2-fc1y.*cos(theta1);r2.*-1.0e2-r2d.*1.0e1+r2s.*1.0e2-fc2y.*cos(theta2)];
