function C = sw_model_C(in1,in2)
%SW_MODEL_C
%    C = SW_MODEL_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Sep-2019 12:28:51

r1 = in1(5,:);
r2 = in1(6,:);
r1d = in2(5,:);
r2d = in2(6,:);
theta1 = in1(3,:);
theta2 = in1(4,:);
theta1d = in2(3,:);
theta2d = in2(4,:);
t2 = sin(theta1);
t3 = sin(theta2);
t4 = theta1d.^2;
t5 = cos(theta1);
t6 = theta2d.^2;
t7 = cos(theta2);
C = [(r1.*t2.*t4)./1.0e1+(r2.*t3.*t6)./1.0e1-(r1d.*t5.*theta1d)./5.0-(r2d.*t7.*theta2d)./5.0;r1.*t4.*t5.*(-1.0./1.0e1)-(r2.*t6.*t7)./1.0e1-(r1d.*t2.*theta1d)./5.0-(r2d.*t3.*theta2d)./5.0-1.1772e1;r1.*(t2.*9.81e2+r1d.*theta1d.*2.0e2).*(-1.0./1.0e3);r2.*(t3.*9.81e2+r2d.*theta2d.*2.0e2).*(-1.0./1.0e3);t5.*(9.81e2./1.0e3)+(r1.*t4)./1.0e1;t7.*(9.81e2./1.0e3)+(r2.*t6)./1.0e1];
